### ISSUE TITLE
compute_bins falls with CUDA out of memory for big datasets

### ISSUE THREAD

**Issue by daniilkk** [yandex-research/rtdl-num-embeddings#18]
Due to the [memory inefficient implementation of torch.quantile](https://github.com/pytorch/pytorch/issues/64947), I get `CUDA out of memory` error when trying to compute bins [here](https://github.com/yandex-research/rtdl-num-embeddings/blob/24173f7023088d48a1a81765029aedd632316d56/package/rtdl_num_embeddings.py#L338)

Temporary workaround: copy your tensor on cpu before passing to `compute_bins`:
`rtdl_num_embeddings.compute_bins(X_train.cpu(), ...)`

**Comment by Yura52** [comment]
Thank you for the report. Since the issue comes from PyTorch itself, it cannot be fixed in this package, but there is now a [warning](https://github.com/yandex-research/rtdl-num-embeddings/blob/abf8a8b35854e4b06476bb48902096b0b58ffce2/package/rtdl_num_embeddings.py#L377) with a helpful message. Perhaps, in future, subsampling should be implemented directly in the `compute_bins` function.
