### ISSUE TITLE
What happens if you concatenate the features to the embedding?

### ISSUE THREAD

**Issue by jamespinkerton** [yandex-research/rtdl-num-embeddings#20]
Hi. I was curious what you think would happen if instead of replacing the features with the Fourier embedding, you instead use both? Is it likely that you’re regularizing and thus losing the effect when you do this, or is it more likely you’re adding valuable features and so the more the merrier.

Thanks for the suggestion!
James

**Comment by Yura52** [comment]
@jamespinkerton Hi, James! One thing to consider is that concatenating the raw feature value to its embedding will often mean explicitly adding a _linear_ type of dependency on this feature from the perspective of the _first_ layer of your model (e.g. MLP). And I think it can depend on the feature, embedding type and the dataset whether it is a good, neutral or bad thing.

In our upcoming project that will be released soon, we use an embedding module where this linear dependency is explicitly added to the feature embedding. Think `Embedding(x) = LinearEmbedding(x) + NonLinearEmbedding(x)` (also, `NonLinearEmbedding` is initialized with zeros, and thus does not have any effect at initialization). This is not a focus of the project at all, just a minor thing, so there will not be any rigorous motivation for this. My informal intuition is that this can be a bit safer to explicitly preserve the linear dependency, because it is a reasonable "default" type of dependency for most tabular features.

Let me know if this helps :) Also, if you have any experiments on this or any intuition, that would be interesting to hear.

**Comment by Yura52** [comment]
The aforementioned new project is now released: https://github.com/yandex-research/tabm

And the new piecewise-linear embeddings used in the TabM project are now available in the `rtdl_num_embeddings` package since v0.0.11, see the [announcement](https://github.com/yandex-research/rtdl-num-embeddings/releases/tag/v0.0.11) for details.

**Comment by Yura52** [comment]
If further help is needed, feel free to reopen the issue!
